# Generated by Django 4.2.4 on 2023-08-14 17:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="borrowing",
        ),
        migrations.DeleteModel(
            name="Borrowing",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
